CREATE TABLE account (
    account_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email         VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (account_id),
    CONSTRAINT uk_account_email UNIQUE (email)
);

-- file_id is generated by the application: the file is written to disk under
-- this name before the row is inserted
CREATE TABLE shared_file (
    file_id       UUID NOT NULL,
    account_id    BIGINT NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    size_bytes    BIGINT NOT NULL,
    password_hash VARCHAR(255),
    uploaded_at   TIMESTAMPTZ NOT NULL,
    expires_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_shared_file PRIMARY KEY (file_id),
    CONSTRAINT fk_shared_file_account FOREIGN KEY (account_id) REFERENCES account (account_id),
    CONSTRAINT ck_shared_file_size CHECK (size_bytes >= 0),
    CONSTRAINT ck_shared_file_expiry CHECK (expires_at > uploaded_at)
);

-- PostgreSQL does not index foreign keys; the history (US05) filters on it
CREATE INDEX idx_shared_file_account ON shared_file (account_id);
